import scrapy
from scrapy.item import Item, Field

class HkjcAllItem(scrapy.Item):

    race_date = Field()
    venue = Field()
    race_no = Field()
    result = Field()
    horse_number = Field()
    horse_name = Field()
    horse_id = Field()
    jockey = Field()
    trainer = Field()
    actual_weight = Field()
    declared_weight = Field()
    draw = Field()
    LBW = Field()
    finish_time = Field()
    win_odds = Field()
    running_pos_1 = Field()
    running_pos_2 = Field()
    running_pos_3 = Field()
    running_pos_4 = Field()
    running_pos_5 = Field()
    running_pos_6 = Field()
    race_code = Field()
    race_class = Field()
    distance = Field()
    handicap = Field()
    prize_money = Field()
    condition = Field()
    track = Field()
    config = Field()
    race_time_1 = Field()
    race_time_2 = Field()
    race_time_3 = Field()
    race_time_4 = Field()
    race_time_5 = Field()
    race_time_6 = Field()
    sectional_time_1 = Field()
    sectional_time_2 = Field()
    sectional_time_3 = Field()
    sectional_time_4 = Field()
    sectional_time_5 = Field()
    sectional_time_6 = Field()
    win_dividend = Field()
    place_dividend = Field()
    quinella = Field()
    qp1_dividend = Field()
    qp1_win_com = Field()
    qp2_dividend = Field()
    qp2_win_com = Field()
    qp3_dividend = Field()
    qp3_win_com = Field()
    tierce = Field()
    trio = Field()
    first_4 = Field()
    quartet = Field()
    url = Field()

class HkjcRaceDayItem(scrapy.Item):

    date = Field()
    venue = Field()
    n_race = Field()

class HkjcNewRaceItem(scrapy.Item):

    race_date = Field()
    venue = Field()
    race_no = Field()
    horse_number = Field()
    horse_name = Field()
    horse_id = Field()
    jockey = Field()
    trainer = Field()
    actual_weight = Field()
    declared_weight = Field()
    draw = Field()
    race_code = Field()
    race_class = Field()
    distance = Field()
    handicap = Field()
    prize_money = Field()
    condition = Field()
    track = Field()
    config = Field()
    url = Field()

class HkjcLiveWinOddsItem(scrapy.Item):

    time_scaped = Field()
    time_updated_by_hkjc = Field()
    race_date = Field()
    venue = Field()
    race_no = Field()
    win_odds_1 = Field()
    win_odds_2 = Field()
    win_odds_3 = Field()
    win_odds_4 = Field()
    win_odds_5 = Field()
    win_odds_6 = Field()
    win_odds_7 = Field()
    win_odds_8 = Field()
    win_odds_9 = Field()
    win_odds_10 = Field()
    win_odds_11 = Field()
    win_odds_12 = Field()
    win_odds_13 = Field()
    win_odds_14 = Field()
    place_odds_1 = Field()
    place_odds_2 = Field()
    place_odds_3 = Field()
    place_odds_4 = Field()
    place_odds_5 = Field()
    place_odds_6 = Field()
    place_odds_7 = Field()
    place_odds_8 = Field()
    place_odds_9 = Field()
    place_odds_10 = Field()
    place_odds_11 = Field()
    place_odds_12 = Field()
    place_odds_13 = Field()
    place_odds_14 = Field()

class HkjcLiveInvestmentItem(scrapy.Item):

    time_scaped = Field()
    time_updated_by_hkjc = Field()
    race_date = Field()
    venue = Field()
    win_investment = Field()
    pla_investment = Field()
    qin_investment = Field()
    qpl_investment = Field()
    tce_investment = Field()
    tri_investment = Field()
    qtt_investment = Field()
    dbl_investment = Field()
    total_investment = Field()